# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, max_length=20)),
                ('street_name', models.CharField(max_length=200)),
                ('street_type', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('residance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaryServer.Address')),
            ],
        ),
    ]
